version: "3.9"

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - postgres
    command: "uvicorn --factory presentation.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
      - ../alembic.ini:/app/alembic.ini
    networks:
      - backend
      - elk-network

networks:
  backend:
    driver: bridge
  elk-network:
    name: elk-network
    driver: bridge
    attachable: true